// Gallery Data Here
export const galleryData = [
  {
    id: "27",
    title: "Portfolio V2 - About",
    caption: "ReactJs - Material Ui",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/k4t2V3cn/protfoliov2.jpg",
    url: "https://i.postimg.cc/7Z9wqxpF/smartmockups-lt2x1c0x.jpg",
  },
  {
    id: "1",
    title: "Age Calculator",
    caption: "ReactJs",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/B6VhMsTd/age.jpg",
    url: "https://i.postimg.cc/grbkLx0s/smartmockups-lt2wtlt8.jpg",
  },

  {
    id: "2",
    title: "Pricing",
    caption: "HTML/CSS",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/bdXmfTFg/buy.jpg",
    url: "https://i.postimg.cc/bNQ2Htt1/smartmockups-lt2wub60.jpg",
  },
  {
    id: "28",
    title: "Portfolio V2 - Gallery",
    caption: "ReactJs - Material Ui",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/8cQjMKKL/protfoliov2-2.jpg",
    url: "https://i.postimg.cc/4xsXCKFv/smartmockups-lt2x1n7h.jpg",
  },
  {
    id: "4",
    title: "Country - DarkMode",
    caption: "ReactJs - Api",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/7ZNrXGfd/country-2.jpg",
    url: "https://i.postimg.cc/MHfpGhyy/smartmockups-lt2wvh6f.jpg",
  },
  {
    id: "5",
    title: "Dashboard Admin - HomePage",
    caption: "first Material Ui Project",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/K8fCB6Wy/dashboard.jpg",
    url: "https://i.postimg.cc/7YT5PTVp/smartmockups-lt2wvq3l.jpg",
  },

  {
    id: "7",
    title: "Dashboard Admin - Dashboard Page",
    caption: "first Material Ui Project",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/LXcWm2Jj/dashboard3.jpg",
    url: "https://i.postimg.cc/x8Bqy00x/smartmockups-lt2wwc6a.jpg",
  },

  {
    id: "11",
    title: "Family Website Landing Page",
    caption: "Html/Css",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/9Q4CXFMn/family.jpg",
    url: "https://i.postimg.cc/sxT4VG4B/smartmockups-lt2wx85k.jpg",
  },
  {
    id: "12",
    title: "NeoMorphism KeyBoard",
    caption: "Html/Css",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/bwK8ZcSN/keyboard.jpg",
    url: "https://i.postimg.cc/2ykxR7hR/smartmockups-lt2wxfce.jpg",
  },

  {
    id: "3",
    title: "Country",
    caption: "ReactJs - Api",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/KvB2ksFZ/country.jpg",
    url: "https://i.postimg.cc/kMRSGZM1/smartmockups-lt2wv7rl.jpg",
  },
  {
    id: "6",
    title: "Dashboard Admin - Products",
    caption: "first Material Ui Project",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/PxpcGP5t/dashboard2.jpg",
    url: "https://i.postimg.cc/DfNWKcqr/smartmockups-lt2ww23u.jpg",
  },
  {
    id: "14",
    title: "Monster Energy - HomePage",
    caption: "ReactJs - Sass",
    year: "2024",
    hoverUrl: "https://i.postimg.cc/cC4Gpd2T/monster-2.jpg",
    url: "https://i.postimg.cc/ZKYw14xB/smartmockups-lt2wy2cw.jpg",
  },
  {
    id: "15",
    title: "Monster Energy - Energy Drinks Page",
    caption: "ReactJs - Sass",
    year: "2024",
    hoverUrl: "https://i.postimg.cc/ZKnhjKr5/monster-3.jpg",
    url: "https://i.postimg.cc/c1BD9rwG/smartmockups-lt2wya47.jpg",
  },
  {
    id: "16",
    title: "Notification ",
    caption: "ReactJs",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/gk7b7FDq/notification.jpg",
    url: "https://i.postimg.cc/sXQrP5vz/smartmockups-lt2wyixs.jpg",
  },
  {
    id: "8",
    title: "Dashboard Admin - Dashboard Page",
    caption: "first Material Ui Project",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/8cL059v9/dashboard4.jpg",
    url: "https://i.postimg.cc/Tw7K1VBX/smartmockups-lt2wwkkr.jpg",
  },
  {
    id: "17",
    title: "Portfolio V1 - HomePage",
    caption: "ReactJs - Material Ui",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/rsp7hQRP/protfoliov1.jpg",
    url: "https://i.postimg.cc/nLwxQ3VT/smartmockups-lt2wyqqw.jpg",
  },

  {
    id: "19",
    title: "React Bootstrap",
    caption: "ReactJs - ReactBootstrap",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/c4rVwkSK/reactbootstrap.jpg",
    url: "https://i.postimg.cc/yNf1yVjm/smartmockups-lt2x1v09.jpg ",
  },
  {
    id: "20",
    title: "React Bootstrap",
    caption: "ReactJs - ReactBootstrap",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/R0zyrMnf/reactbootstrap-2.jpg",
    url: "https://i.postimg.cc/hG44mJL4/smartmockups-lt2x24ub.jpg",
  },
  {
    id: "10",
    title: "Education Responsive Landing Page",
    caption: "Html/Css",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/V6nRBMNb/education.jpg",
    url: "https://i.postimg.cc/fTgfpXbp/smartmockups-lt2wwzud.jpg",
  },
  {
    id: "21",
    title: "Sabzlearn Project",
    caption: "ReactJs",
    year: "2024",
    hoverUrl: "https://i.postimg.cc/W35HJgY6/sabzlearn.jpg",
    url: "https://i.postimg.cc/3xFJWjDb/smartmockups-lt2x2bkn.jpg",
  },
  {
    id: "22",
    title: "Sabzlearn Project - Register Page",
    caption: "ReactJs",
    year: "2024",
    hoverUrl: "https://i.postimg.cc/sx10PxtF/sabzlearn2.jpg",
    url: "https://i.postimg.cc/3JpwQQrh/smartmockups-lt2x2k2d.jpg",
  },
  {
    id: "13",
    title: "Monster Energy - HomePage",
    caption: "ReactJs - Sass",
    year: "2024",
    hoverUrl: "https://i.postimg.cc/Jn8LQNQf/monster.jpg",
    url: "https://i.postimg.cc/pLD5CHby/smartmockups-lt2wxoru.jpg",
  },
  {
    id: "23",
    title: "Weather App",
    caption: "ReactJs",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/pdqZ0xQP/temp.jpg",
    url: "https://i.postimg.cc/LsvKFNZ2/smartmockups-lt2x2tnw.jpg",
  },
  {
    id: "24",
    title: "Testimonial",
    caption: "ReactJs",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/W3z7CKSg/testimonial2.jpg",
    url: "https://i.postimg.cc/gJkpxfPx/smartmockups-lt2x3a7f.jpg",
  },
  {
    id: "25",
    title: "Testimonial",
    caption: "ReactJs",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/tJ026kt6/testimonial.jpg",
    url: "https://i.postimg.cc/pLbtf9Hb/smartmockups-lt2x3442.jpg",
  },
  {
    id: "18",
    title: "Portfolio V1 - AboutMe",
    caption: "ReactJs - Material Ui",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/BbwkRHxQ/protfoliov1-2.jpg",
    url: "https://i.postimg.cc/pddxTwvp/smartmockups-lt2wz448.jpg",
  },
  {
    id: "25",
    title: "TodoApp",
    caption: "ReactJs",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/8sQBFCGm/todolist.jpg",
    url: "https://i.postimg.cc/Dymzj4HS/smartmockups-lt2x3lrp.jpg",
  },
  {
    id: "9",
    title: "Dashboard Admin - Login Page",
    caption: "first Material Ui Project",
    year: "2023",
    hoverUrl: "https://i.postimg.cc/rFLHbyXk/dashboard5.jpg",
    url: "https://i.postimg.cc/SsNXmTTr/smartmockups-lt2wwrqo.jpg",
  },
];
