export const galleryData = [
  {
    id: "27",
    title: "Portfolio V2 - About",
    caption: "ReactJs - Material Ui",
    year: "2023",
    url: "https://i.postimg.cc/k4t2V3cn/protfoliov2.jpg",
  },
  {
    id: "1",
    title: "Age Calculator",
    caption: "ReactJs",
    year: "2023",
    url: "https://i.postimg.cc/B6VhMsTd/age.jpg",
  },

  {
    id: "2",
    title: "Pricing",
    caption: "HTML/CSS",
    year: "2023",
    url: "https://i.postimg.cc/bdXmfTFg/buy.jpg",
  },
  {
    id: "28",
    title: "Portfolio V2 - Gallery",
    caption: "ReactJs - Material Ui",
    year: "2023",
    url: "https://i.postimg.cc/8cQjMKKL/protfoliov2-2.jpg",
  },
  {
    id: "4",
    title: "Country - DarkMode",
    caption: "ReactJs - Api",
    year: "2023",
    url: "https://i.postimg.cc/7ZNrXGfd/country-2.jpg",
  },
  {
    id: "5",
    title: "Dashboard Admin - HomePage",
    caption: "first Material Ui Project",
    year: "2023",
    url: "https://i.postimg.cc/K8fCB6Wy/dashboard.jpg",
  },

  {
    id: "7",
    title: "Dashboard Admin - Dashboard Page",
    caption: "first Material Ui Project",
    year: "2023",
    url: "https://i.postimg.cc/LXcWm2Jj/dashboard3.jpg",
  },

  {
    id: "11",
    title: "Family Website Landing Page",
    caption: "Html/Css",
    year: "2023",
    url: "https://i.postimg.cc/9Q4CXFMn/family.jpg",
  },
  {
    id: "12",
    title: "NeoMorphism KeyBoard",
    caption: "Html/Css",
    year: "2023",
    url: "https://i.postimg.cc/bwK8ZcSN/keyboard.jpg",
  },

  {
    id: "3",
    title: "Country",
    caption: "ReactJs - Api",
    year: "2023",
    url: "https://i.postimg.cc/KvB2ksFZ/country.jpg",
  },
  {
    id: "6",
    title: "Dashboard Admin - Products",
    caption: "first Material Ui Project",
    year: "2023",
    url: "https://i.postimg.cc/PxpcGP5t/dashboard2.jpg",
  },
  {
    id: "14",
    title: "Monster Energy - HomePage",
    caption: "ReactJs - Sass",
    year: "2024",
    url: "https://i.postimg.cc/cC4Gpd2T/monster-2.jpg",
  },
  {
    id: "15",
    title: "Monster Energy - Energy Drinks Page",
    caption: "ReactJs - Sass",
    year: "2024",
    url: "https://i.postimg.cc/ZKnhjKr5/monster-3.jpg",
  },
  {
    id: "16",
    title: "Notification ",
    caption: "ReactJs",
    year: "2023",
    url: "https://i.postimg.cc/gk7b7FDq/notification.jpg",
  },
  {
    id: "8",
    title: "Dashboard Admin - Dashboard Page",
    caption: "first Material Ui Project",
    year: "2023",
    url: "https://i.postimg.cc/8cL059v9/dashboard4.jpg",
  },
  {
    id: "17",
    title: "Portfolio V1 - HomePage",
    caption: "ReactJs - Material Ui",
    year: "2023",
    url: "https://i.postimg.cc/rsp7hQRP/protfoliov1.jpg",
  },

  {
    id: "19",
    title: "React Bootstrap",
    caption: "ReactJs - ReactBootstrap",
    year: "2023",
    url: "https://i.postimg.cc/c4rVwkSK/reactbootstrap.jpg",
  },
  {
    id: "20",
    title: "React Bootstrap",
    caption: "ReactJs - ReactBootstrap",
    year: "2023",
    url: "https://i.postimg.cc/R0zyrMnf/reactbootstrap-2.jpg",
  },
  {
    id: "10",
    title: "Education Responsive Landing Page",
    caption: "Html/Css",
    year: "2023",
    url: "https://i.postimg.cc/V6nRBMNb/education.jpg",
  },
  {
    id: "21",
    title: "Sabzlearn Project",
    caption: "ReactJs",
    year: "2024",
    url: "https://i.postimg.cc/W35HJgY6/sabzlearn.jpg",
  },
  {
    id: "22",
    title: "Sabzlearn Project - Register Page",
    caption: "ReactJs",
    year: "2024",
    url: "https://i.postimg.cc/sx10PxtF/sabzlearn2.jpg",
  },
  {
    id: "13",
    title: "Monster Energy - HomePage",
    caption: "ReactJs - Sass",
    year: "2024",
    url: "https://i.postimg.cc/Jn8LQNQf/monster.jpg",
  },
  {
    id: "23",
    title: "Weather App",
    caption: "ReactJs",
    year: "2023",
    url: "https://i.postimg.cc/pdqZ0xQP/temp.jpg",
  },
  {
    id: "24",
    title: "Testimonial",
    caption: "ReactJs",
    year: "2023",
    url: "https://i.postimg.cc/W3z7CKSg/testimonial2.jpg",
  },
  {
    id: "25",
    title: "Testimonial",
    caption: "ReactJs",
    year: "2023",
    url: "https://i.postimg.cc/tJ026kt6/testimonial.jpg",
  },
  {
    id: "18",
    title: "Portfolio V1 - AboutMe",
    caption: "ReactJs - Material Ui",
    year: "2023",
    url: "https://i.postimg.cc/BbwkRHxQ/protfoliov1-2.jpg",
  },
  {
    id: "25",
    title: "TodoApp",
    caption: "ReactJs",
    year: "2023",
    url: "https://i.postimg.cc/8sQBFCGm/todolist.jpg",
  },
  {
    id: "9",
    title: "Dashboard Admin - Login Page",
    caption: "first Material Ui Project",
    year: "2023",
    url: "https://i.postimg.cc/rFLHbyXk/dashboard5.jpg",
  },
];
