export const skills = [
  { name: "HTML, CSS, SCSS" },
  { name: "JavaScript (ES6+)" },
  { name: "TypeScript" },
  { name: "React, Redux Toolkit" },
  { name: "Bootstrap" },
  { name: "TailwindCss" },
  { name: "Zustand, Context API" },
  { name: "React Router" },
  { name: "Node.js, Express.js" },
  { name: "RESTful APIs" },
  { name: "MongoDB, Mongoose" },
  { name: "Authentication, Authorization" },
  { name: "JWT, Bcrypt" },
  { name: "Git, GitHub" },
  { name: "Zod" },
  { name: "Material-UI", tag: "Familiar" },
  { name: "Framer Motion", tag: "Familiar" },
  { name: "Formik / Yup", tag: "Familiar" },
];
